version: '3.7'
services:
  lazylibrarian:
    image: linuxserver/lazylibrarian:1ae32b40-ls30
    container_name: lazylibrarian
    hostname: lazylibrarian
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - ../Data/config:/config
      - ../Data/downloads:/downloads
      - ../Data/books:/books
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.lazylibrarian.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.lazylibrarian.entrypoints=web-secure"
        #- "traefik.http.routers.lazylibrarian.middlewares=default-headers@file"
      - "traefik.http.routers.lazylibrarian.service=lazylibrarian"
      - "traefik.http.routers.lazylibrarian.tls=true"
      - "traefik.http.services.lazylibrarian.loadbalancer.server.port=5299" # Proxied Port
